---
title: "Sabrina Carpenter Portfolio"
author: "Alida Plas"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---
### Introduction

PLEASE DO NOT SHOW THIS PORTFOLIO IN CLASS
The collection of music that I would like to learn more about are the songs of Sabrina Carpenter. I choose this artist, because I have been listening to her music for 7 years now and I am a big fan. I grew up with her, but she also did and her music has changed a lot over time. Sabrina’s first single came out in March 2014 when she was 14 years old. She is now 22 and in the mean time she released four albums and many singles. Since her music is so different, I wonder how Spotify makes a list of music that relates to her music.
My comparison points will be the artist Sabrina Carpenter and the Spotify artist radio. Does Spotify make the list very similar to the artist's music or is there a big difference? I do think that major differences between these playlist will be timbre. Every artist has its own manner of singing.
Some typical songs in the artist radio are the songs from Sabrina Carpenter herself. 
In my first plot you can see that Sabrina's music is spread over the whole graph. Compared to the radio everything is close together in a kind of line.

```{r}
```


